---
title: "git_01"
author: "Daniella Parra"
date: "Summer 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
And cannot pleasures, while they last,   
Be actual unless, when past,   
They leave us shuddering and aghast,   
With anguish smarting?   
And cannot friends be firm and fast,    
And yet bear parting?  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,    
Some say in ice.    
From what I've tasted of desire.   
I hold with those who favor fire.    
But if it had to perish twice,    
I think I know enough of hate.    

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining with all his might:    
He did his very best to make.   
      The billows smooth and bright —    
And this was odd, because it was.   
      The middle of the night.    
The moon was shining sulkily,    
      Because she thought the sun.   
Had got no business to be there.   
      After the day was done —    
"It's very rude of him," she said,   
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
You can keep calling.   
all of us crazy    
and overdramatic,    
you can write off    
my poetry as just me    
being an obsessive b**ch,     
you can say your ex    
who warned me to stay away    
is just bitter and out to get you,    
but maybe its you.   
for once,    
could you consider.  
that its not us?    
that maybe    
you don't just    
find yourself dating. 